const cartType = {
  ADD_CART_ONE: "ADD_CART_ONE",
  ADD_CART_NEW: "ADD_CART_NEW",
  DELETE_CART_ONE: "DELETE_CART_ONE",
  MINUS_CART_ONE: "MINUS_CART_ONE",
  VIEW_CART:"VIEW_CART",
  ClOSE_CART:"ClOSE_CART",
  CLEAR_CART:"CLEAR_CART",
};

export default cartType;
