const productTypes = {
  
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  VIEW_PRODUCT_START:"VIEW_PRODUCT_START",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  RESET_VIEW_PRODUCT: "RESET_VIEW_PRODUCT",
  CHOOSE_COLOR: "CHOOSE_COLOR",
  CHOOSE_SIZE:"CHOOSE_SIZE",
  RESET_AFTER_ADD_CART:"RESET_AFTER_ADD_CART",
};

export default productTypes;
